### ISSUE TITLE
feat: add `infIsNA`?

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/QFeatures#105]
I have implemented an [`infIsNA`](https://github.com/UCLouvain-CBIO/scp/blob/92f78503ffc604ab36f637c3e38b43e52dfaec0c/R/transform.R#L96-L120) function in the `scp` package. It replaces any infinite value by `NA`. This occurs when dividing data by a reference sample that contains 0. 

I am wondering whether this function should be provided by `QFeatures` rather than `scp`. What do you think? 

I could convert the function to a method so that it behaves like `zeroIsNA`.

**Comment by lgatto** [comment]
Yes, I think it would be a better fit for `QFeatures`, as it is very general.
