### ISSUE TITLE
Standardized header for rowData

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/QFeatures#112]
Hi,

as far as I can see and as far as I tested it, the rowData can have arbitrary header. Should there be a minimal set of headers that are consistently named? E.g. `mz`, `rtime`, etc. User could supply mappings e.g. `RTmin` should be converted from minutes to seconds and the header named `rtime` 
@sneumann @jorainer 

Best regards,

Michael

**Comment by lgatto** [comment]
No, there is no such thing in `QFeatures`, and there's no reason for any of these. There is for the `Spectra` class though.

**Comment by michaelwitting** [comment]
Okay, thx. I was just wondering, because in metabolomics we also use quantitative data from non-identified metabolites, which would be represented by `mz` and `rtime`

**Comment by lgatto** [comment]
In that case, have a look at the [`MsFeatures`](https://github.com/rformassspectrometry/MsFeatures) package. We will organise a call at some point to discuss the roadmap of that package and invite you and others for input and suggestions.
