### ISSUE TITLE
rowData function not working for QFeatures

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/QFeatures#113]
Hi,

`rowData` is not working for me and my PhD student, while `colData` and `rowDataNames` is. Tested on Windows and MacOS.

Best regards,

Michael

**Comment by lgatto** [comment]
Indeed, and that is because there's no `rowData,QFeatures` method:
```r
> library("QFeatures")
> showMethods("rowData")
Function: rowData (package SummarizedExperiment)
x="SummarizedExperiment"
```
You can get a list of rowData 

```r
lapply(experiments(object), rowData)
```
A `rowData,QFeatures` method wrapping the above could be added if there's enough interest

Cc: @cvanderaa

**Comment by cvanderaa** [comment]
Indeed, this can be linked to issue #86

**Comment by lgatto** [comment]
OK, PR welcome, I suppose.

**Comment by lgatto** [comment]
There now is a `rowData,QFeatures` method that returns a `List` of row data.
