### ISSUE TITLE
longFormat that also includes rowData

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/QFeatures#116]
I'm using `longFormat` really a lot. It's a bit frustrating that the function allows to include `colData` fields (`colDataCols`), but not `rowData` fields (e.g. `rowDataCols`) whilethere is no reason this should not be possible. 

Therefore, I have implemented this locally in `scp`, but I'm sure it has a better place in `QFeatues`, or maybe we should suggest this in `MultiAssayExperiment`.

**Comment by lgatto** [comment]
This is definitely something to be used more widely. I suggest you send a PR to `QFeatures` and then, we can get in touch with `MAE` to see if they are interested.
