### ISSUE TITLE
custom imputation functions

### ISSUE THREAD

**Issue by ococrook** [rformassspectrometry/QFeatures#121]
Mostly useful for developers but it would be great to be able to write an custom impute function and pass it to impute. Stupid example below:

```{r,}
myImputeFunction <- function(x, r){
x[is.na(x)] <- r
}
```
Something like the following would be nice
```{r,}
impute(myobject, method = myImputeFunction, methargs = list(r = 1))
```

**Comment by lgatto** [comment]
There's a low-level implemention in [`MsCoreUtils::impute_fun()`](https://github.com/rformassspectrometry/MsCoreUtils/pull/78). Need to check it it works out of the box from the method.

**Comment by lgatto** [comment]
Works with `QFeatures::impute()` using `MsCoreUtils` version >= 1.3.2 available with `BiocManager::install("RforMassSpectrometry/MsCoreUtils")`. The version has also been pushed to Bioconductor and should be available in 24 hours or so.

**Comment by lgatto** [comment]
By the way, there is an `MsCoreUtils::impute_with()` function that implement you suggestion above, just in case. Appy it with `method = "with"`.

**Comment by ococrook** [comment]
perfect thanks Laurent
