### ISSUE TITLE
QFeatures visualisation vignette

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#146]
@cvanderaa - it would be good to add a (static) plot of a complex QFeatures object in the visualisation vignette.

**Comment by cvanderaa** [comment]
By complex, do you mean with several branching points? If so, I think this test data might be useful to plot, see here the output: 

![image](https://user-images.githubusercontent.com/43441105/126294354-b75e3d49-f1ff-4be2-8e2f-200db49fc8be.png)

(I here realize that the plotting function still needs some tweaking to better spread the nodes)

I guess we could export the data generated in [this test script](https://github.com/rformassspectrometry/QFeatures/blob/5b2d48779633be583d39c40cb18bbc73032e3eee/tests/testthat/test_subsetByFeatures.R#L20-L34) as an example data set?

**Comment by lgatto** [comment]
yes, something like that
