### ISSUE TITLE
ExperimentList error

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/QFeatures#35]
Using the `hl` object from here https://rformassspectrometry.github.io/Features/articles/Features.html I get an error if I try to use `ExperimentList`. Shouldn't that work?

I am trying to make an object from the XCMS output with both grouped and ungrouped peaks. So far I am failing miserably but I ran into this that seemed like a bug.

```r
ExperimentList(hl)
```

```r
Fejl i validObject(.Object) : invalid class "ExperimentList" object: 
    ExperimentList elements must be named
In addition: Advarselsbesked:
I max(y) : no non-missing arguments to max; returning -Inf
```

**Comment by lgatto** [comment]
Indeed. Weird though that the following works
```
> hl@ExperimentList
ExperimentList class object of length 2:
 [1] psms: SummarizedExperiment with 32776 rows and 10 columns
 [2] peptides: SummarizedExperiment with 26796 rows and 10 columns
> names(hl@ExperimentList)
[1] "psms"     "peptides"
```
Thank you for the report, I'll investiage.

**Comment by lgatto** [comment]
This is also confirmed upstream - see https://github.com/waldronlab/MultiAssayExperiment/issues/265

**Comment by lgatto** [comment]
Please use `experiments(hl)`. As noted by @LiNk-NY, `ExperimentList` is actually the constructor, and `experiments` the accessor.

**Comment by stanstrup** [comment]
Doh! :(
