### ISSUE TITLE
linking assays without reference in the source

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/QFeatures#36]
Hello,

this is probably not a bug but rather me that don't understand how I could do what I am trying to do.

I am trying to get the results from XCMS into a `Features` object. The trick is that I wanted to have the raw peaks as one assay and the grouped peaks as another assay. Then I could add assays for CAMERA etc.

I think I have managed to add the assays in a same way but I have not been able to get them linked correctly.

To avoid adding a grouping variable to the ungrouped data I tried to use `AssayLink(hits =...) `.

Am I doing something completely stupid or do you have some hint of what goes wrong? I am not understanding what it is comparing in the error I get.

```r
# libraries ---------------------------------------------------------------
library(Features)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibble)

xset_g <- readRDS("xset_g.rds")
file_info <- readRDS("file_info.rds")



# Extract peak info -------------------------------------------------------
# ungrouped peaks
peaks <- xset_g %>% 
              chromPeaks %>% 
              as.data.frame() %>% 
              rownames_to_column("peakidx") %>% 
              left_join(file_info, by = "sample") %>% 
              as_tibble %>% 
              pivot_wider(id_cols = c(file, msLevel, peakidx, mz, mzmin, mzmax, rt, rtmin, rtmax, dppm, scale, scpos, scmin, scmax, lmin,  lmax), names_from = sample, values_from = into)


# grouped peaks / features
feat_quant <- xset_g %>% 
                featureValues(value = "into", method = "maxint") %>% 
                set_colnames(as.character(file_info[,"sample"]))
  
  

# Make Features object ----------------------------------------------------
# ungrouped peaks
Feat_obj <-  peaks %>% 
               select(-file,  -msLevel) %>% 
               readFeatures(ecol = as.character(file_info[,"sample"]), fnames = "peakidx", name = "peaks_into")

colData(Feat_obj) <- file_info %>% DataFrame(., row.names = .$sample)


# create link index
link <- featureDefinitions(xset_g) %>%
            as.data.frame %>% 
            mutate(feature_idx = 1:n()) %>% 
            select(feature_idx, peakidx) %>%
            unnest(peakidx) %>% 
            mutate_all(as.integer) %>% 
            {AssayLink(from = "peaks_into", 
                       name = "features_into", 
                       hits = Hits(from=.$feature_idx, 
                                   to=.$peakidx, 
                                   nLnode=nrow(feat_quant),
                                   nRnode=nrow(peaks)
                                   )
                      )
            }



# add grouped features
Feat_obj <- addAssay(Feat_obj,
                     SummarizedExperiment(feat_quant), 
                     name = "features_into", 
                     assayLinks = link
                     )



# error :(
Feat_obj %>% subsetByFeature("FT0001")
```

-->

```r
Error in alnks[featurename_list] : 
  identical(names(x), names(i)) is not TRUE
```

[data.zip](https://github.com/rformassspectrometry/Features/files/4103270/data.zip)

**Comment by lgatto** [comment]
I think what is missing is the `fcol` in the `features_intro` part of the assay link. It corresponds to the `name` argument in `aggregateFeatures`, defining how to aggregate the rows of the first assay (`peaks_into` in your case).

```r
> str(Feat_obj@assayLinks)
Formal class 'AssayLinks' [package "Features"] with 4 slots
  ..@ listData       :List of 2
  .. ..$ peaks_into   :Formal class 'AssayLink' [package "Features"] with 4 slots
  .. .. .. ..@ name: chr "peaks_into"
  .. .. .. ..@ from: chr NA
  .. .. .. ..@ fcol: chr NA
  .. .. .. ..@ hits:Formal class 'Hits' [package "S4Vectors"] with 6 slots
  .. .. .. .. .. ..@ from           : int(0) 
  .. .. .. .. .. ..@ to             : int(0) 
  .. .. .. .. .. ..@ nLnode         : int 0
  .. .. .. .. .. ..@ nRnode         : int 0
  .. .. .. .. .. ..@ elementMetadata: NULL
  .. .. .. .. .. ..@ metadata       : list()
  .. ..$ features_into:Formal class 'AssayLink' [package "Features"] with 4 slots
  .. .. .. ..@ name: chr "features_into"
  .. .. .. ..@ from: chr "peaks_into"
  .. .. .. ..@ fcol: chr NA ## <---- MISSING
  .. .. .. ..@ hits:Formal class 'Hits' [package "S4Vectors"] with 6 slots
  .. .. .. .. .. ..@ from           : int [1:10931] 1 1 1 1 1 1 1 2 3 4 ...
  .. .. .. .. .. ..@ to             : int [1:10931] 1585 3305 5210 5211 7051 8838 10751 8187 8186 8188 ...
  .. .. .. .. .. ..@ nLnode         : int 7895
  .. .. .. .. .. ..@ nRnode         : int 10933
  .. .. .. .. .. ..@ elementMetadata: NULL
  .. .. .. .. .. ..@ metadata       : list()
  ..@ elementType    : chr "AssayLink"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()
```
This links are created automatically by the `aggregateFeatures` function upon creation of the new assays. 

The goal would be to make it easy to create such links for assays, as you are doing, but I didn't get the time to do so yet. Ideally, a function that takes a `Features` object, two assays, and the `rowData` columns that link them should return an updated `Feature` with the new `AssayLink`.

**Comment by lgatto** [comment]
Note to self: suggested signature for such a function

```r
createAssayLink(object, ## Features object
                c(1, 2), ## indices or names of assays to link
                fcol)  ## the name of the shared feature variable in the respective rowData.
```

**Comment by stanstrup** [comment]
OK thanks.
So you have to have a column in both assays that link them?
Creating the mapping indexes in hits is not enough?
That is what I was trying to avoid so that the source assay did not need to be changed when you make derived information. Changing the source material somehow seems counter to having a clear progression of analysis.

**Comment by lgatto** [comment]
> Creating the mapping indexes in hits is not enough?

Apparently not, but I am not sure. The reason I am not sure is that the development was done with the main use case in mind, i.e. creating these linked assays using `aggreteFeatures`, and thus, by definition, leads to such a shared column. In theory, I agree it isn't mandatory. 

Your use case is of course perfectly relevant, and it might lead to some updates to these assay links. I will try to get some work on this done, at least clearer documentation and requirements next week.

**Comment by lgatto** [comment]
Following up from your report, the issue is not the missing `fcol`. The metadata slot in the second assay (`peptides` below) is actually what is missing.

```r
Browse[2]> str(x@assayLinks)
Formal class 'AssayLinks' [package "Features"] with 4 slots
  ..@ listData       :List of 2
  .. ..$ psms    :Formal class 'AssayLink' [package "Features"] with 4 slots
  .. .. .. ..@ name: chr "psms"
  .. .. .. ..@ from: chr NA
  .. .. .. ..@ fcol: chr NA
  .. .. .. ..@ hits:Formal class 'Hits' [package "S4Vectors"] with 6 slots
  .. .. .. .. .. ..@ from           : int(0) 
  .. .. .. .. .. ..@ to             : int(0) 
  .. .. .. .. .. ..@ nLnode         : int 0
  .. .. .. .. .. ..@ nRnode         : int 0
  .. .. .. .. .. ..@ elementMetadata: NULL
  .. .. .. .. .. ..@ metadata       : list()
  .. ..$ peptides:Formal class 'AssayLink' [package "Features"] with 4 slots
  .. .. .. ..@ name: chr "peptides"
  .. .. .. ..@ from: chr "psms"
  .. .. .. ..@ fcol: chr "Sequence"
  .. .. .. ..@ hits:Formal class 'SortedByQueryHits' [package "S4Vectors"] with 6 slots
  .. .. .. .. .. ..@ from           : int [1:32776] 1 2 3 4 4 5 5 6 7 8 ...
  .. .. .. .. .. ..@ to             : int [1:32776] 11701 13678 31499 8109 10298 12846 27617 10671 312 13879 ...
  .. .. .. .. .. ..@ nLnode         : int 26796
  .. .. .. .. .. ..@ nRnode         : int 32776
  .. .. .. .. .. ..@ elementMetadata:Formal class 'DataFrame' [package "S4Vectors"] with 6 slots
  .. .. .. .. .. .. .. ..@ rownames       : NULL
  .. .. .. .. .. .. .. ..@ nrows          : int 32776
  .. .. .. .. .. .. .. ..@ listData       :List of 2
  .. .. .. .. .. .. .. .. ..$ names_to  : chr [1:32776] "aAAAAAAAAAAAAAAGAAGk" "AAAAAAAAAAAAAAAGAAGk" "aAAAADLANR" "aAAAAGGk" ...
  .. .. .. .. .. .. .. .. ..$ names_from: chr [1:32776] "11701" "13678" "31499" "8109" ...
  .. .. .. .. .. .. .. ..@ elementType    : chr "ANY"
  .. .. .. .. .. .. .. ..@ elementMetadata: NULL
  .. .. .. .. .. .. .. ..@ metadata       : list()
  .. .. .. .. .. ..@ metadata       : list()
  ..@ elementType    : chr "AssayLink"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()
```

This [slot is accessed](https://github.com/rformassspectrometry/Features/blob/master/R/subsetBy-methods.R#L106) in the `subsetByFeature` method. This could probably be replaced by using the `queryHits` and `subjectHits` instead... as long as row order is maintained. I will further investigate.

**Comment by cvanderaa** [comment]
Maybe a bit late, but @stanstrup you can make your custom linking work if you adapt your `create link index` section a bit:
```r
# create link index
idxInPeaks <- featureDefinitions(xset_g) %>%
  as.data.frame %>% 
  mutate(idx = 1:n()) %>% 
  unnest(peakidx) %>% 
  select(idx) %>%
  unlist(use.names = FALSE)
idxInFeat <- 1:nrow(feat_quant)
hits <- findMatches(idxInPeaks, idxInFeat)
elementMetadata(hits)$names_to <- rownames(feat_quant)[hits@to]
elementMetadata(hits)$names_from <- rownames(Feat_obj[["peaks_into"]])[hits@from]
link <- AssayLink(from = "peaks_into", 
                  name = "features_into", 
                  hits = hits)
```
The first pipe does some indexing that is somewhat different from what you did (but makes inserting metadata more straightforward). `idxInPeaks` is the index of the features from `feat_quant` in `peaks`. `idxInFeat`  is the index of the features from `feat_quant` in `feat_quant` (trivial index). 

It then creates a `Hits` object from the indexing and inserts the corresponding row names from the `to` (`feat_quant`) and the `from` (`peaks_into`) data in the `elementMetadata` slot as suggested by @lgatto .

Check the `hits` object
```
Hits object with 10931 hits and 2 metadata columns:
          queryHits subjectHits |    names_to  names_from
          <integer>   <integer> | <character> <character>
      [1]         1           1 |      FT0001     CP00001
      [2]         2           1 |      FT0001     CP00002
      [3]         3           1 |      FT0001     CP00003
      [4]         4           1 |      FT0001     CP00004
      [5]         5           1 |      FT0001     CP00005
      ...       ...         ... .         ...         ...
  [10927]     10927        7893 |      FT7893     CP10927
  [10928]     10928        7893 |      FT7893     CP10928
  [10929]     10929        7894 |      FT7894     CP10929
  [10930]     10930        7894 |      FT7894     CP10930
  [10931]     10931        7895 |      FT7895     CP10931
  -------
  queryLength: 10931 / subjectLength: 7895
```
Notice the columns `names_to` and `names_from` are coming from the `elementMetadata` slot and are later used for subsetting the row of your assays.  So, you can create any custom link between data within your `Features` object as long as indexing and metadata information are provided (and correct).

**Comment by stanstrup** [comment]
Great! Thanks! I am back to working on this now.
Is this still the best way or can the new  addAssayLink and addAssayLinkOneToOne functions be used? It is not clear to me how if it is the case.

**Comment by lgatto** [comment]
If you aggregate features, then the `aggregateFeatures` function will create the assay link automatically.

Otherwise, the recommended way is to use the new `addAssayLink` and `addAssayLinkOneToOne` functions. They are documented [here](https://rformassspectrometry.github.io/Features/reference/AssayLinks.html). Let us know if you identify any bugs or if things are unclear.

**Comment by stanstrup** [comment]
If I understand correctly those functions still need a column to exist in both datasets that can be matched right?
So doesn't help directly here unless I misunderstood.

It doesn't seem like @cvanderaa's suggestion gave me the right linking. But it was very useful in me trying to figure it out.
The following seems to give the expected linking:

```r
hits <- featureDefinitions(xset_g) %>%
          as.data.frame %>%
          mutate(feature_idx = 1:n()) %>%
          select(feature_idx, peakidx) %>%
          unnest(peakidx) %>%
          mutate_all(as.integer) %>%
          
          Hits(to  =unname(.$feature_idx),
               from=unname(.$peakidx),
               nRnode=nrow(feat_quant),
               nLnode=nrow(peaks),
               sort.by.query = TRUE
          )

elementMetadata(hits) <- NULL

elementMetadata(hits)$names_to <- rownames(feat_quant)[hits@to]
elementMetadata(hits)$names_from <- rownames(Feat_obj[["peaks_into"]])[hits@from]

link <- AssayLink(from = "peaks_into", 
                  name = "features_into", 
                  hits = hits)


Feat_obj <- addAssay(Feat_obj,
                     SummarizedExperiment(feat_quant), 
                     name = "features_into", 
                     assayLinks = link
                     )


Feat_obj %>% subsetByFeature("FT00031") %>% .[[1]] %>% assay
Feat_obj %>% subsetByFeature("FT00031") %>% .[[2]] %>% assay

```

**Comment by stanstrup** [comment]
In case this is useful to anyone here is a generalized function:

```r


addMapped_Assay <- function(Feat_obj, parent_assay, new_assay, child_assay, mapping){
  
  
  hits <- Hits(to  =unname(mapping$to),
               from=unname(mapping$from),
               nRnode=nrow(new_assay),
               nLnode=nrow(Feat_obj[[parent]]),
               sort.by.query = TRUE
  )
  
  
  
  elementMetadata(hits) <- NULL
  
  elementMetadata(hits)$names_to <- rownames(new_assay)[hits@to]
  elementMetadata(hits)$names_from <- rownames(Feat_obj[[parent]])[hits@from]
  
  link <- AssayLink(from = parent_assay, 
                    name = child_assay, 
                    hits = hits)
  
  
  

new_Feature_obj <- addAssay(Feat_obj,
                     new_assay, 
                     name = child_assay, 
                     assayLinks = link
                     )


return(new_Feature_obj)


}


Feat_obj <- addMapped_Assay(Feat_obj = Feat_obj, 
                            parent_assay =  "peaks_into", 
                            new_assay = feature_assay, 
                            child_assay = "features_into", 
                            mapping = mapping
                            )

```

**Comment by cvanderaa** [comment]
Thanks for the feedback and the updated solution! You're right you need a feature variable in both assays that links them. Your function is valid, but I still would advise you to go for the `addAssayLink` as it does what `addMapped_Assay` but IMHO that is more readable (let me know if you disagree).

Below is my version of the solution that uses `addAssayLink`. This time, I checked we are generating the same `Hits` object for the new `AssayLink` (I did not do this in my last comment, sorry for that). I will pick up from your `# Make Features object` section in your first comment. So here I generate the `Features` object with one assay as you did:
```r
Feat_obj <-  peaks %>% 
    select(-file,  -msLevel) %>% 
    readFeatures(ecol = as.character(file_info[,"sample"]), fnames = "peakidx", name = "peaks_into")
colData(Feat_obj) <- file_info %>% DataFrame(., row.names = .$sample)
``` 
Then, I add the `features_into` assay. Note that I omit the `assayLinks` argument so no link between assays is generated. 
```r
Feat_obj <- addAssay(Feat_obj,
                    SummarizedExperiment(feat_quant), 
                    name = "features_into")
```
Next, I need the mapping between the two assays. I copy-pasted the code you used for generating the `Hits` object but I keep it in `data.frame` format.
```r
mapping <- featureDefinitions(xset_g) %>%
    as.data.frame %>%
    mutate(feature_idx = 1:n()) %>%
    select(feature_idx, peakidx) %>%
    unnest(peakidx) %>%
    mutate_all(as.integer)
```
I can now create the linking feature variables. In the `feature_into` assay, this is a simple indexing of the rows.
```r
rowData(Feat_obj[["features_into"]])$FeatureIdx <- 1:nrow(Feat_obj[["features_into"]])
```
In the `peaks_into` assay, I add the Feature index using `mapping`. This is the critical part (I hope it is clear enough) and you need this to be right in order to create the correct links between the two assays.
```r 
rowData(Feat_obj[["peaks_into"]])$FeatureIdx <- 
    mapping$feature_idx[match(1:nrow(Feat_obj[["peaks_into"]]), mapping$peakidx)]
```
Finally, I simply call `addAssayLink` and refer to the matching variable.
```r
Feat_obj <- addAssayLink(Feat_obj, from = "peaks_into", to = "features_into",
                        varFrom = "FeatureIdx", varTo = "FeatureIdx")
```
What do you think of this ?

**Comment by lgatto** [comment]
Beyond the preference and readability of the different solutions, one note of importance is the **validity** of the `Features` objects. There are additional changes of the class in the pipeline. Using the official API (`addAssayLink` in this case) will guarantee that the object will be and remain valid.

**Comment by stanstrup** [comment]
Thanks!
Yes this is more straight forward and less hacky.

I am wondering again if the link is completely right or I am doing something wrong again...
I tried to do:
```r
filterFeatures(Feat_obj, ~ FeatureIdx == 1L)
```
But get `Error: logical subscript contains NAs`

Shouldn't I be able to do that? `subsetByFeature` works.

My use case was that I wanted to add some more annotation:
```r
rowData(Feat_obj[["features_into"]]) <- rowData(Feat_obj[["features_into"]]) %>% 
                                          cbind(CAM_anno)
```

And be able to do:
```r
filterFeatures(Feat_obj, ~ pcgroup == 5340L)
```

But that results in:
```r
harmonizing input:
  removing 20 sampleMap rows not in names(experiments)
Error in .valid_assay_links(object) : @from not valid
```

[CAM_anno.zip](https://github.com/rformassspectrometry/Features/files/4450472/CAM_anno.zip)

**Comment by cvanderaa** [comment]
For your first problem, this is indeed not expected. It seems related to your mapping as 2 features in `features_into` are not matched to any features in `peaks_into`. See here the check (a bit hacky I admit):
```r
sum(diff(sort(mapping$peakidx)) != 1) 
## 2
```
This is also true with your solution 
```r
sum(diff(hits@from) != 1)
## 2
```
Either something is wrong with how `mapping` or `hits` (see above) are generated or there is something wrong with the data. Either way, this is not related to the package. If there is a good reason that the 2 features in `features_into` were not coming from any features in `peaks_into`, I would suggest your to remove them
```r
filterFeatures(Feat_obj, ~ !is.na(FeatureIdx))
```

**Comment by cvanderaa** [comment]
For the second error, this is indeed a bug we are currently working on (issue #58).

**Comment by lgatto** [comment]
The `NA` is indeed a bug, reported in #60. 

As for the second error, it is probably something like #58. We are in the processed of addressing this.

**Comment by stanstrup** [comment]
Thanks for all the help.

@cvanderaa Isn't it the other way around? There are features in `peaks_into` that are not part of any feature in `features_into`. That is expected. But should it be a problem?
So perhaps this is indeed the #60 problem?

**Comment by cvanderaa** [comment]
Wait sorry, it is another bug we are experiencing here. Indeed the way around is expected and this is happening for 3036 features. The issue here is that a single feature in `features_into` is originating from two different features in `peaks_into`... See
 
```r
mapping[6673:6680, ]
```
```
# A tibble: 8 x 2
  feature_idx peakidx
        <int>   <int>
1        4431    4835
2        4432    1267
3        4433    3042
4        4433    6798
5        4434    3030
6        4434    8256
7        4435    1275
8        4436    3034
```
`feature_idx` 4433 originated from `peakidx` 3042 **and** 6798 

@lgatto correct me if I'm wrong, but I think we only support m:1 and 1:1 relationships. Should we also implement 1:n and m:n relationships (adjacency matrix could become very handy here)?

**Comment by lgatto** [comment]
I am confirming that, at the moment, we only support 1:1 relationships when [aggregating assays](https://rformassspectrometry.github.io/Features/reference/Features-aggregate.html) - the aggregation is defined by a vector, and hence a row of the starting assay is mapped to a single row in the aggregated assay. In [MSnbase::combineFeatures()](http://lgatto.github.io/MSnbase/reference/combineFeatures.html), 1:n relations are supported, with the use of a list to define the aggregation procedure. This will be added to `aggregateFeatures` in due time. 

Note however that nothing is enforced in terms of 1:1 relations in the assay links or the `subsetByFeatures` function. I would need a simpler reproducible example to explore this in more details.

**Comment by lgatto** [comment]
Also, note that #58 is *now* fixed.

**Comment by stanstrup** [comment]
Just leaving a reference here that as far I as understand we need #52 for this to work.

**Comment by lgatto** [comment]
@stanstrup - I don't think so: adding a one-to-one link is already available. #52 deals with links when the `joinAssay()` function is used and leads to the new assay to have >1 parent. @cvanderaa can confirm if there are other dependencies that I might haven missed.

**Comment by cvanderaa** [comment]
@lgatto I think the last commits have solved the main issue highlighted in this issue. 

@stanstrup I think your example now works with the latest version of `Features`. Here is the full example (taking the data you shared in your previous comments) that should hopefully do what is expected. If you still spot problems, could you please open a new issue?

```r
# libraries ---------------------------------------------------------------
library(Features)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibble)

xset_g <- readRDS("~/Desktop/xset_g.rds")
file_info <- readRDS("~/Desktop/file_info.rds")
CAM_anno <-readRDS("~/Desktop/CAM_anno.rds")

# Extract peak info -------------------------------------------------------
# ungrouped peaks
peaks <- xset_g %>% 
  chromPeaks %>% 
  as.data.frame() %>% 
  rownames_to_column("peakidx") %>% 
  left_join(file_info, by = "sample") %>% 
  as_tibble %>% 
  pivot_wider(id_cols = c(file, msLevel, peakidx, mz, mzmin, mzmax, rt, rtmin, rtmax, dppm, scale, scpos, scmin, scmax, lmin,  lmax), names_from = sample, values_from = into)

# grouped peaks / features
feat_quant <- xset_g %>% 
  featureValues(value = "into", method = "maxint") %>% 
  set_colnames(as.character(file_info[,"sample"]))

# Create Features object --------------------------------------------------
# Add the peak assay
Feat_obj <-  peaks %>% 
  select(-file,  -msLevel) %>% 
  readFeatures(ecol = as.character(file_info[,"sample"]), fnames = "peakidx", name = "peaks_into")
colData(Feat_obj) <- file_info %>% DataFrame(., row.names = .$sample)

# Add the features assay
Feat_obj <- addAssay(Feat_obj,
                     SummarizedExperiment(feat_quant), 
                     name = "features_into")

# Link the two assays ----------------------------------------------------
# Create the peak to features mapping
mapping <- featureDefinitions(xset_g) %>%
  as.data.frame %>%
  mutate(feature_idx = 1:n()) %>%
  select(feature_idx, peakidx) %>%
  unnest(peakidx) %>%
  mutate_all(as.integer)

# Include the mapping in the rowData
rowData(Feat_obj[["features_into"]])$FeatureIdx <- 1:nrow(Feat_obj[["features_into"]])
rowData(Feat_obj[["peaks_into"]])$FeatureIdx <- 
  mapping$feature_idx[match(1:nrow(Feat_obj[["peaks_into"]]), mapping$peakidx)]

# Create the AssayLink from the mapping 
Feat_obj <- addAssayLink(Feat_obj, from = "peaks_into", to = "features_into",
                         varFrom = "FeatureIdx", varTo = "FeatureIdx")

# Adding extra metadata --------------------------------------------------
# Metadata from the CAM_anno
rowData(Feat_obj[["features_into"]]) <- rowData(Feat_obj[["features_into"]]) %>% 
  cbind(CAM_anno[1:nrow(Feat_obj[["features_into"]]), ])
# Note CAM_anno has dim = 15487 x 3 which don't match any dim in Feat_obj

# Check everything works -------------------------------------------------
# Check filterFeatures on new meta variable
rowData(filterFeatures(Feat_obj, ~ pcgroup == 5340L)[["features_into"]])$pcgroup
# Make sure the Features object is still valid
validObject(Feat_obj)
```
