### ISSUE TITLE
One-to-one assay links

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#42]
In processing function (log, scale, impute, normalise, ...), when new assays are added to a `Features` object using `addAssay`, need a way to record the one-to-one links between features.

**Comment by lgatto** [comment]
I remember you showing me some code that implemented this - is it somewhere in a PR?

**Comment by cvanderaa** [comment]
I have code for this in branch `issue42` on [my fork](https://github.com/cvanderaa/Features/tree/issue42). I still need to double-check the code I wrote, add some documentation and make sure I included all required unit tests. 

I will send a PR soon, but I think it is safer if I PR it to a separate branch on `rformasspectrometry`. Could you maybe open a branch called `issue42` in the repository?

**Comment by lgatto** [comment]
Done.
