### ISSUE TITLE
Implement assay renaming

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/QFeatures#47]
I would like to rename my assays contained in a `Feature` object. I naively tried:
```
library(Features)
data("hlpsms")
fts <- readFeatures(hlpsms, ecol = 1:10)
validObject(fts)
names(fts) <- "foo"
validObject(fts)
```
But `validObject(fts)` throws the following error: 
```
## Error during wrapup: Assay links names are wrong.
```
Maybe we could implement a `name<-` method ?

**Comment by lgatto** [comment]
Working on it.

**Comment by lgatto** [comment]
@cvanderaa - have you send the PR for this yet?

**Comment by cvanderaa** [comment]
Yes, but I have sent a PR to your own `renaming` branch so to `lgatto/Features/tree/renaming/`. You need to send a PR from `lgatto` to `rformassspectrometry`.

**Comment by lgatto** [comment]
Merged now.
