### ISSUE TITLE
bug: `Features()` throws error since last update from `MultiAssayExperiment`

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/QFeatures#53]
`Features` fails to  build with latest version of `MultiAssayExperiment`, since [this](https://github.com/waldronlab/MultiAssayExperiment/commit/460f3fc074103580be5c0f7b0ae6a8514c63c0f2) commit. 

The `Features()` constructor should be adapted for this change.

**Comment by lgatto** [comment]
See also [this issue](https://github.com/waldronlab/MultiAssayExperiment/issues/268).
