### ISSUE TITLE
Joining assays

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#59]
```
joinAssays(Features, c("pep_batch1", "pep_batch2", "pep_batch3"), name = "peptides", type = "full")
joinAssays(Features, c(1, 2, 3), name = "peptides", type = "inner")
```
See devel notes.

**Comment by lgatto** [comment]
I decided to drop the `type` argument to only have a full join. If an inner join is needed, then filtering features with NA after joining would be equivalent. Other alternatives are only relevant when joining 2 assays. 

```
joinAssays(Features, c("pep_batch1", "pep_batch2", "pep_batch3"), name = "peptides")
joinAssays(Features, c(1, 2, 3), name = "peptides")
```

The current stage of this can be seen in branch `issue59`, file [`Features-join.R`](https://github.com/rformassspectrometry/Features/blob/issue59/R/Features-join.R).

**Comment by lgatto** [comment]
There is now a fully documented and tested `joinAssays` function in `issue59`. 

Still to be done:
- When joining assays, consider setting the `Features`' `colData`, if missing.
- Add the `AssayLink` linking to the parent assays (needs #52)

**Comment by lgatto** [comment]
@cvanderaa - could you try the new function. You can install latest version from branch `issue59` with
```r
remotes::install_github("RforMassSpectrometry/Features", ref = "issue59")
```

**Comment by cvanderaa** [comment]
Thanks a lot it works for the SCP dataset I'm working on ([Specht et al 2019](https://www.biorxiv.org/content/10.1101/665307v1))!
