### ISSUE TITLE
Filtering features with NAs

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#60]
Here's an example:
```r
> library(Features)
> example(aggregateFeatures)
> filterFeatures(feat1, ~  location == "Mitochondrion")
A instance of class Features containing
 [1] psms: SummarizedExperiment with 6 rows and 2 columns 
 [2] peptides: SummarizedExperiment with 2 rows and 2 columns 
 [3] proteins: SummarizedExperiment with 1 rows and 2 columns 
```
but
```r
> rowData(feat1[[1]])$location[1] <- NA
> filterFeatures(feat1, ~  location == "Mitochondrion")
Error: logical subscript contains NAs
```
It is clear where the error [comes from](https://github.com/rformassspectrometry/Features/blob/master/R/Features-filter.R#L194), when `sel` has `NA`s, and then

```r
> feat1[[1]][c(NA, TRUE, rep(FALSE, 8)), ]
Error: logical subscript contains NAs
```

This could be fixed in `filterFeaturesWithAnnotationFilter` and `filterFeaturesWithFormula` and replacing the `NA`s in the logical vector by `FALSE`. Before, it would be good to check with the `AnnotationFilter` maintainer @jorainer - do you have any suggestion as to best handle this from the filtering point of view?

**Comment by jorainer** [comment]
No solution for that in `AnnotationFilter` - unfortunately. Would a workaround with `which` work?

**Comment by lgatto** [comment]
Yes, that would also catch only those that are `TRUE`. Thank you for the suggestion.

**Comment by lgatto** [comment]
The proper action in such a situation would actually be first explicitly handle missing values
```r
> filterFeatures(feat1, ~  !is.na(location)) %>% 
    filterFeatures(~ location == "Mitochondrion")
A instance of class Features containing
 [1] psms: SummarizedExperiment with 5 rows and 2 columns 
 [2] peptides: SummarizedExperiment with 2 rows and 2 columns 
 [3] proteins: SummarizedExperiment with 1 rows and 2 columns 
```
I am wondering if an `na.rm` argument to `filterFeatures` wouldn't be an option. If the missing values are discarded, it should at least be with a message.

**Comment by lgatto** [comment]
The intended fix was to have an `na.rm` , that would keep the rows with an `NA` (for the default `na.rm = FALSE`) and remove them (for `na.rm = FALSE`). The code in the `filterFeature` function would be something like
```r
sel <- lapply(sel, function(x) {
    x[is.na(x)] <- !na.rm
    x
})
```

I thought this would be an easy fix but it actually isn't at all. `NA` values in the row data have **much** deeper effects, that I will document elsewhere (see [here](https://rformassspectrometry.github.io/Features/reference/Features-aggregate.html) and [here](https://rformassspectrometry.github.io/Features/reference/reduceDataFrame.html)). 

I will not commit anything and keep this issue open for the moment until the implications of missing data in the row data have been documented.

**Comment by jorainer** [comment]
maybe `%in%` could be an alternative?

`~ location %in% "Mitochondrion"` should be similar to `which` by returning only those that match and are **not** `NA`, `~ location %in% c(NA, "Mitochondrion")` should return you all that are either `NA` or match your keyword.

**Comment by lgatto** [comment]
Thank you @jorainer, that's indeed a great solution too.
