### ISSUE TITLE
Count number of peptides in aggregateFeatures()

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#75]
Following up from a discussion with @statOmics, the `msqrob` hurdle model requires peptides counts to assess whether a feature is differentially detected if it can't be tested for differential expression. 

It would be useful to all to calculate the number of peptides per protein per sample as part of the `aggregateFeatures()`. It remains to be seen whether this peptide count matrix is to be stored as an additional assay in the aggregated `SummarizedExperiment` or in the `rowData`.

**Comment by lgatto** [comment]
In addition, irrespective where the counts matrix ends up, it will be useful to have an accessor - for example ~~`aggregationCounts()`~~ `aggcounts()`.

**Comment by statOmics** [comment]
The accessor is a great idea. With an accessor it is not so important for our developments where the count matrix ends up...

**Comment by lgatto** [comment]
@statOmics - see PR #76. Expect it to become available tomorrow, which requires `MsCoreUtils` 1.1.2 (all currently a [PR](https://github.com/rformassspectrometry/MsCoreUtils/pull/54)).  

The accessor is called `aggcounts()`, to be in line with `SingleCellExperiment::counts()`, `SingleCellExperiment::logcounts()`, ...

**Comment by lgatto** [comment]
A quick vote here to name the aggregation count accessor. Currently, we have

1. **`aggcounts()`**: short, in line with other existing assay accessors such as `SingleCellExperiment::counts()`, `SingleCellExperiment::logcounts()`, ... but does sound like [*aggressive counts*](https://github.com/rformassspectrometry/Features/pull/76#discussion_r431610034) for previous discussion)).
2. **`aggregationCounts()`**: explicit, longer, no aggressive tone.

- To vote for 1: :+1: 
- To vote for 2: :-1: 
- Other suggestion: comment below and upvote that suggestion.

Ping @jorainer, @statOmics, @cvanderaa, @sgibb
