### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#89]
- The term *features* has multiple definitions.
- The new [MsFeatures](https://github.com/rformassspectrometry/MsFeatures/) package will deal with features in LC-MS space. 

In the light of these two points, I am wondering if this package shouldn't be renamed `QFeatures` (for quantitative). 

Pro: 
- avoid confusion
- package isn't on Bioconductor yet

Con:
- we already have `Features` stickers :-/

Comments? @jorainer @sgibb @cvanderaa

**Comment by cvanderaa** [comment]
I think you mean **LC**-MS. I'm not sure to understand what `MsFeatures` will do. If the user will first process the data with `MsFeatures` then uses `QFeatures` for further processing that seems very good to me, but if the two packages are unrelated, I think it is confusing they have similar names.

**Comment by jorainer** [comment]
I would be OK with keeping the `Features` package as it is but `QFeatures` would also be good. And yes, for now `MsFeatures` is thought to deal with LC-MS features (that have a specific rtime and m/z), but I would also not limit it to that. What I would also try to add there is functionality to group features based on their m/z alone (e.g. find the *feature* that is the isotope of another feature) or also group MS features by similarity of their MS2 spectra.

The biggest difference I see at present is that `Features` deals with a quantitative *feature* matrix and performs aggregation functions on that, while the `MsFeatures` package I have in my mind does **not** do any aggregations, but provides functions to *define* groups of features (essentially the column/factor that can be used by `Features` to establish the grouping). Maybe `GroupFeatures` would be an alternative name for the package, but I usually don't want to have a verb in a package name...

**Comment by lgatto** [comment]
A for LC-MS features, they currently have a specific rtime and m/z value, but could also be defined by drift times, so that's also a further dimension for possible grouping (or discrimination). I definitely like `MsFeatures` as a name. 

Let me think a bit further about the `[Q]Features` idea. Anyway, I suggest we defer these decisions to the discussions after our respective holiday.

**Comment by lgatto** [comment]
And to reply to @cvanderaa, there is a relation between `MsFeatures` and `[Q]Features`, but I am under the impression that it till needs to be defined more precisely.

**Comment by lgatto** [comment]
Another point related to package (re-)naming: What about all the functions that contain the work _Features_ such as `readFeatures()`, `filterFeatures()`, `aggregateFeatures()`, ... Would we want to rename them to `readQFeatures()`, `filterQFeatures()`, `aggregateQFeatures()`

- Yes, at least for those that would strictly relate to quantitative features (i.e operate on matrices)
- No if we want to have the name function name to work on quantitative features and LC-MS features. 

Same applies for the `MsFeatures` package, of course.

**Comment by lgatto** [comment]
Side effects of this change:
- [x] dependencies (for example `msqrob2`)
- [x] *RforMassSpectrometry* webpage
- [X] `Features` is mentioned in the `MsCoreUtilse` vignette
- [X] Change Github repo name
- Sticker :-(

**Comment by sneumann** [comment]
Hi, renaming is welcome, also in light of https://cran.r-project.org/web/packages/features/ Yours, Steffen
